### ISSUE TITLE
Бот публикует предложку группы сразу на стену (при использовании LongPoll)

### ISSUE THREAD

**Issue by mrgulka** [qwertyadrian/TG_AutoPoster#31]
**Опишите ошибку**
Бот публикует предложку группы сразу на стену

**Как получить ошибку**
Шаги для воспроизведения ошибки:
1. Тестовая группа-страница с предложкой
2. Создать ключ сообщества LongPoll со всеми правами и вписать в конфиг
3. Запустить бота
4. С левой страницы попробовать что-то написать в предложку группы
5. Бот опубликует это сообщение в телеграме

**Ожидаемое поведение**
Не хотелось бы, чтобы бот отправлял предложку без моего разрешения

**Лог-файл**
Загрузите лог-файл бота, запущенного в режиме отладки (параметр `--debug`).
```
2023-04-01 20:51:48.415 | INFO     | __main__:<module>:97 - TG AutoPoster запущен
2023-04-01 20:51:48.417 | DEBUG    | __main__:<module>:98 - Python 3.11.1 (main, Jan  9 2023, 20:37:01) [GCC 12.2.1 20220924]
TG_AutoPoster 3.4.0
OS: linux
Config path: /data/config.yaml
Cache dir: /tmp/TG_AutoPosterbudwnx0n
Passed args:['--debug']
/usr/local/lib/python3.11/site-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2023-04-01 20:51:48.668 | INFO     | TG_AutoPoster.TG_AutoPoster:listen:148 - [VK] Для источника https://vk.com/gulstore включен режим Long Poll API
2023-04-01 20:51:53.672 | INFO     | TG_AutoPoster.TG_AutoPoster:get_new_posts:145 - [VK] Проверка завершена
```
**далее все как обычно**

Если дать только право "стена", то выдаёт это:

```
Job "AutoPoster.listen (trigger: date[2023-04-01 20:51:48 UTC], next run at: 2023-04-01 20:51:48 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.4.0-py3.11.egg/TG_AutoPoster/TG_AutoPoster.py", line 162, in listen
    longpoll = VkBotLongPoll(self.vk_session, group_id=-group.group_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vk_api/bot_longpoll.py", line 219, in __init__
    self.update_longpoll_server()
  File "/usr/local/lib/python3.11/site-packages/vk_api/bot_longpoll.py", line 232, in update_longpoll_server
    response = self.vk.method('groups.getLongPollServer', values)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vk_api/vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [15] Access denied: no access to call this method
```

**Дополнительная информация**

**Comment by mrgulka** [comment]
лучший, спасибо🥰
