### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by LexsaTV** [qwertyadrian/TG_AutoPoster#32]
Последние дня 3-4 стабильно ближе к вечеру начинаются зависания проверок и при скачивание картинок и дальше бот зависает, можно раз по 10 пере запускать и иногда все таки пробивается
```
Job "AutoPoster.get_new_posts (trigger: interval[1:00:00], next run at: 2023-04-05 21:44:13 EEST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/vk/TG_AutoPoster/TG_AutoPoster.py", line 125, in get_new_posts
    for post in chain(group.get_posts(), group.get_stories()):
  File "/home/vk/TG_AutoPoster/utils/vk/group.py", line 93, in get_posts
    yield from self.get_post(post)
  File "/home/vk/TG_AutoPoster/utils/vk/group.py", line 121, in get_post
    parsed_post.parse_post()
  File "/home/vk/TG_AutoPoster/utils/vk/parser.py", line 70, in parse_post
    self.parse_photo(attachment["photo"])
  File "/home/vk/TG_AutoPoster/utils/vk/parser.py", line 154, in parse_photo
    photo = download(photo, bar=None)
  File "/usr/local/lib/python3.8/dist-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

```

**Comment by qwertyadrian** [comment]
Бот здесь не причём. Вероятнее всего проблема с интернет соединением или же с серверами ВК.
Я могу сделать пропуск скачивания проблеменых картинок после нескольких неудачных попыток.

**Comment by LexsaTV** [comment]
Понятно что дело не с ботом, но может не хватает каких то проверок?
Потому что бот может стопатся и просто на проверке постов так и при скачивание улетать в тайм аут
Тупое но рабочее решение просто поставить проверку постов каждую минуту, он думает по 3-4 минуты улетает в тайм аут и через минуту снова идет по списку проверки новых постов и снова либо виснет либо скачивает и идет дальше 
А пропускать картинки это не вариант все таки, а нужно просто пытаться скачать а пока что заставляю как белку бегать по кругу 
Бот стоит на выделенном сервере нормальном платном
