### ISSUE TITLE
не запускается контейнер

### ISSUE THREAD

**Issue by mrgulka** [qwertyadrian/TG_AutoPoster#33]
**Опишите ошибку**
не запускается контейнер, просит модуль 'крипто'

**Как получить ошибку**
Шаги для воспроизведения ошибки:
1. запуллить ```docker pull qwertyadrian/tg_autoposter:master```
2. заранить ```docker run -it --name tgautoposter -v /root:/data 3ab97fb78456```
3. получить 
```
root@main:~# docker start -ai 7a8b6ef9d21f
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/TG_AutoPoster.py", line 14, in <module>
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/utils/__init__.py", line 3, in <module>
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/utils/vk/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/utils/vk/group.py", line 9, in <module>
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/utils/vk/parser.py", line 14, in <module>
  File "/usr/local/lib/python3.11/site-packages/TG_AutoPoster-3.5.0b1-py3.11.egg/TG_AutoPoster/utils/vk/tools.py", line 8, in <module>
ModuleNotFoundError: No module named 'Crypto'
```

**Ожидаемое поведение**
ожидал запустить бота

**Лог-файл**
логов нет

**Ваш ПК (пожалуйста, укажите следующую информацию):**
linux сервер

**Дополнительная информация**

**Comment by mrgulka** [comment]
наверное это глупо, но я это не понимаю s(

**Comment by mrgulka** [comment]
закинул поддержать на киви чисто символически🥰
