### ISSUE TITLE
Ошибка постинга

### ISSUE THREAD

**Issue by LexsaTV** [qwertyadrian/TG_AutoPoster#45]
Все работало а вчера упало в ошибку

Job "AutoPoster.get_new_posts (trigger: interval[0:10:00], next run at: 2023-12-17 11:32:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/vk/TG_AutoPoster/TG_AutoPoster.py", line 127, in get_new_posts
    for post in chain(group.get_posts(), group.get_stories()):
  File "/home/vk/TG_AutoPoster/utils/vk/group.py", line 93, in get_posts
    yield from self.get_post(post)
  File "/home/vk/TG_AutoPoster/utils/vk/group.py", line 108, in get_post
    if re.findall(
  File "/usr/lib/python3.10/re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0

**Comment by qwertyadrian** [comment]
Какой список стоп-слов используется?
С каким постом происходит ошибка?

Скорее всего проблема с регулярным выражением в списке стоп-слов.
Если проблема наблюдается со всеми постами удалите или исправьте неверное регулярное выражение.

**Comment by LexsaTV** [comment]
Реально проблема была в стоп слове, добавил номер +7 в запрет
Убрал + и все заработало
