### ISSUE TITLE
Ошибка: CERTIFICATE_VERIFY_FAILED. Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by spaceVpn** [qwertyadrian/TG_AutoPoster#47]
**Опишите ошибку**
До сегодняшнего дня работало отлично. 
Утром запустил и получил ошибку CERTIFICATE_VERIFY_FAILED.
Как это можно исправить?

**Лог-файл**
PS C:\Users\Nick\Desktop\telegram_to_vk-master\TG_AutoPoster-master> py -m TG_AutoPoster --sleep 300
Job "AutoPoster.get_new_posts (trigger: interval[0:05:00], next run at: 2024-02-04 11:57:01 MSK)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\Desktop\telegram_to_vk-master\TG_AutoPoster-master\TG_AutoPoster\TG_AutoPoster.py", line 127, in get_new_posts
    for post in chain(group.get_posts(), group.get_stories()):
  File "C:\Users\Nick\Desktop\telegram_to_vk-master\TG_AutoPoster-master\TG_AutoPoster\utils\vk\group.py", line 93, in get_posts
    yield from self.get_post(post)
  File "C:\Users\Nick\Desktop\telegram_to_vk-master\TG_AutoPoster-master\TG_AutoPoster\utils\vk\group.py", line 121, in get_post
    parsed_post.parse_post()
  File "C:\Users\Nick\Desktop\telegram_to_vk-master\TG_AutoPoster-master\TG_AutoPoster\utils\vk\parser.py", line 70, in parse_post
    self.parse_photo(attachment["photo"])
  File "C:\Users\Nick\Desktop\telegram_to_vk-master\TG_AutoPoster-master\TG_AutoPoster\utils\vk\parser.py", line 154, in parse_photo
    photo = download(photo, bar=None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nick\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)>

**Ваш ПК (пожалуйста, укажите следующую информацию):**
 - OS: [Windows]
 - Python Version: [3.11.1]
 - Версия бота [e.g. 3.5.0]
 - Источник установки (GitHub)

**Comment by qwertyadrian** [comment]
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)

Проблема не с ботом. Ошибка состоит в том, что сайт (судя по строке `photo = download(photo, bar=None)` сайт ВК) имел на момент загрузки фото самоподписанный сертификат. Перезапуск бота через некоторое время должен исправить проблему. Так же возможно проблема в использовании VPN/прокси.
